angular.module(
  'client',
  [
    'ngSanitize',
    'ui.router',
    'templates',
    'ngResource',
    'ngAnimate',
    'ngEnter',
    'DatePicker',
    'NgActive',
    'Tooltip',
    'SiteHeader',
    'Backstretch',
    'Timepicker',
    'SearchComponents',
    'GmapAutocomplete'
  ]
)
